QBShared = QBShared or {}
QBShared.Vehicles = QBShared.Vehicles or {}

local Vehicles = {
    --- Compacts (0)
    {
        model = 'asbo',        -- This has to match the spawn code of the vehicle
        name = 'Asbo',         -- This is the display of the vehicle
        brand = 'Maxwell',     -- This is the vehicle's brand
        price = 12000,          -- The price that the vehicle sells for
        category = 'compacts', -- Catgegory of the vehilce, stick with GetVehicleClass() options https://docs.fivem.net/natives/?_0x29439776AAA00A62
        type = 'automobile',   -- Vehicle type, refer here https://docs.fivem.net/natives/?_0x6AE51D4B & here https://docs.fivem.net/natives/?_0xA273060E
        shop = 'luxury',          -- Can be a single shop or multiple shops. For multiple shops for example {'shopname1','shopname2','shopname3'}
    },
    { model = 'blista',        name = 'Blista',                        brand = 'Dinka',           price = 32000,   category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'brioso',        name = 'Brioso R/A',                    brand = 'Grotti',          price = 40000,   category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'club',          name = 'Club',                          brand = 'BF',              price = 15000,    category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'dilettante',    name = 'Dilettante',                    brand = 'Karin',           price = 16000,    category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'kanjo',         name = 'Blista Kanjo',                  brand = 'Dinka',           price = 22000,   category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'issi2',         name = 'Issi',                          brand = 'Weeny',           price = 25000,    category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'issi3',         name = 'Issi Classic',                  brand = 'Weeny',           price = 12000,    category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'panto',         name = 'Panto',                         brand = 'Benefactor',      price = 12000,    category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'prairie',       name = 'Prairie',                       brand = 'Bollokan',        price = 25000,   category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'rhapsody',      name = 'Rhapsody',                      brand = 'Declasse',        price = 22000,   category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'brioso2',       name = 'Brioso 300',                    brand = 'Grotti',          price = 8000,   category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'weevil',        name = 'Weevil',                        brand = 'BF',              price = 13000,    category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'issi7',         name = 'Issi Sport',                    brand = 'Weeny',           price = 70000,  category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'blista2',       name = 'Blista Compact',                brand = 'Dinka',           price = 17000,   category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'brioso3',       name = 'Brioso 300 Widebody',           brand = 'Grotti',          price = 14000,  category = 'compacts',       type = 'automobile', shop = 'luxury' },
    { model = 'boor',          name = 'Boor',                          brand = 'Karin',           price = 23000,   category = 'compacts',       type = 'automobile', shop = 'luxury' },
    
    --- Sedans (1)
    { model = 'asea',          name = 'Asea',                          brand = 'Declasse',        price = 15000,    category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'asterope',      name = 'Asterope',                      brand = 'Karin',           price = 38000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'cog55',         name = 'Cognoscenti 55',                brand = 'Enus',            price = 80000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'cognoscenti',   name = 'Cognoscenti',                   brand = 'Enus',            price = 145000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'emperor',       name = 'Emperor',                       brand = 'Albany',          price = 16000,    category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'fugitive',      name = 'Fugitive',                      brand = 'Cheval',          price = 78000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'glendale',      name = 'Glendale',                      brand = 'Benefactor',      price = 27000,    category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'glendale2',     name = 'Glendale Custom',               brand = 'Benefactor',      price = 99000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'ingot',         name = 'Ingot',                         brand = 'Vulcar',          price = 28000,    category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'intruder',      name = 'Intruder',                      brand = 'Karin',           price = 35000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'premier',       name = 'Premier',                       brand = 'Declasse',        price = 20000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'primo',         name = 'Primo',                         brand = 'Albany',          price = 35000,    category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'regina',        name = 'Regina',                        brand = 'Dundreary',       price = 20000,    category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'stafford',      name = 'Stafford',                      brand = 'Enus',            price = 68500,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'stanier',       name = 'Stanier',                       brand = 'Vapid',           price = 46500,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'stratum',       name = 'Stratum',                       brand = 'Zirconium',       price = 38000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'superd',        name = 'Super Diamond',                 brand = 'Enus',            price = 520000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'surge',         name = 'Surge',                         brand = 'Cheval',          price = 53200,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'tailgater',     name = 'Tailgater',                     brand = 'Obey',            price = 72000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'warrener',      name = 'Warrener',                      brand = 'Vulcar',          price = 43000,    category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'washington',    name = 'Washington',                    brand = 'Albany',          price = 42500,    category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'tailgater2',    name = 'Tailgater S',                   brand = 'Obey',            price = 130000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'cinquemila',    name = 'Lampadati',                     brand = 'Cinquemila',      price = 95000,  category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'iwagen',        name = 'Obey',                          brand = 'I-Wagen',         price = 225000,  category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'astron',        name = 'Astron',                        brand = 'Pfister',         price = 250000,  category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'baller7',       name = 'Baller ST',                     brand = 'Gallivanter',     price = 225000,  category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'comet7',        name = 'Comet',                         brand = 'S2 Cabrio',       price = 420000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'deity',         name = 'Deity',                         brand = 'Enus',            price = 721000,  category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'jubilee',       name = 'Jubilee',                       brand = 'Enus',            price = 645000,  category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'oracle',        name = 'Oracle',                        brand = 'Übermacht',       price = 50000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'schafter2',     name = 'Schafter',                      brand = 'Benefactor',      price = 73000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'warrener2',     name = 'Warrener HKR',                  brand = 'Vulcar',          price = 41000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'rhinehart',     name = 'Rhinehart',                     brand = 'Übermacht',       price = 140000,  category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'eudora',        name = 'Eudora',                        brand = 'Willard',         price = 60000,   category = 'sedans',         type = 'automobile', shop = 'luxury' },
    { model = 'asterope2',     name = 'Asterope GZ',                   brand = 'Karin',           price = 29000,   category = 'sedans',        type = 'automobile', shop = 'luxury' },
    
    --- SUV (2)
    { model = 'baller',        name = 'Baller',                        brand = 'Gallivanter',     price = 140000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'baller2',       name = 'Baller II',                     brand = 'Gallivanter',     price = 190000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'baller3',       name = 'Baller LE',                     brand = 'Gallivanter',     price = 320000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'baller4',       name = 'Baller LE LWB',                 brand = 'Gallivanter',     price = 370000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'bjxl',          name = 'BeeJay XL',                     brand = 'Karin',           price = 67000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'cavalcade',     name = 'Cavalcade',                     brand = 'Albany',          price = 85000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'cavalcade2',    name = 'Cavalcade II',                  brand = 'Albany',          price = 92000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'contender',     name = 'Contender',                     brand = 'Vapid',           price = 193000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'dubsta',        name = 'Dubsta',                        brand = 'Benefactor',      price = 195000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'dubsta2',       name = 'Dubsta Luxury',                 brand = 'Benefactor',      price = 210000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'fq2',           name = 'FQ2',                           brand = 'Fathom',          price = 105000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'granger',       name = 'Granger',                       brand = 'Declasse',        price = 320000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'gresley',       name = 'Gresley',                       brand = 'Bravado',         price = 130000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'habanero',      name = 'Habanero',                      brand = 'Emperor',         price = 55000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'huntley',       name = 'Huntley S',                     brand = 'Enus',            price = 110000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'landstalker',   name = 'Landstalker',                   brand = 'Dundreary',       price = 89000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'landstalker2',  name = 'Landstalker XL',                brand = 'Dundreary',       price = 200000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'novak',         name = 'Novak',                         brand = 'Lampadati',       price = 156500,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'patriot',       name = 'Patriot',                       brand = 'Mammoth',         price = 105000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'radi',          name = 'Radius',                        brand = 'Vapid',           price = 89000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'rebla',         name = 'Rebla GTS',                     brand = 'Übermacht',       price = 160000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'rocoto',        name = 'Rocoto',                        brand = 'Obey',            price = 135000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'seminole',      name = 'Seminole',                      brand = 'Canis',           price = 61000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'seminole2',     name = 'Seminole Frontier',             brand = 'Canis',           price = 59000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'serrano',       name = 'Serrano',                       brand = 'Benefactor',      price = 85000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'toros',         name = 'Toros',                         brand = 'Pegassi',         price = 462000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'xls',           name = 'XLS',                           brand = 'Benefactor',      price = 120000,   category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'granger2',      name = 'Granger 3600LX',                brand = 'Declasse',        price = 201100,  category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'aleutian',      name = 'Aleutian',                      brand = 'Vapid',           price = 190000,  category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'cavalcade3',    name = 'Cavalcade XL',                  brand = 'Albany',          price = 110000,  category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'dorado',        name = 'Dorado',                        brand = 'Bravado',         price = 75000,  category = 'suvs',           type = 'automobile', shop = 'luxury' },
    { model = 'vivanite',      name = 'Vivanite',                      brand = 'Karin',           price = 85000,  category = 'suvs',           type = 'automobile', shop = 'luxury' },
    
    --- Coupes (3)
    { model = 'cogcabrio',     name = 'Cognoscenti Cabrio',            brand = 'Enus',            price = 156000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'exemplar',      name = 'Exemplar',                      brand = 'Dewbauchee',      price = 145000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'f620',          name = 'F620',                          brand = 'Ocelot',          price = 245000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'felon',         name = 'Felon',                         brand = 'Lampadati',       price = 90000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'felon2',        name = 'Felon GT',                      brand = 'Lampadati',       price = 100000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'jackal',        name = 'Jackal',                        brand = 'Ocelot',          price = 73000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'oracle2',       name = 'Oracle XS',                     brand = 'Übermacht',       price = 78000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'sentinel',      name = 'Sentinel',                      brand = 'Übermacht',       price = 90000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'sentinel2',     name = 'Sentinel XS',                   brand = 'Übermacht',       price = 90000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'windsor',       name = 'Windsor',                       brand = 'Enus',            price = 855000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'windsor2',      name = 'Windsor Drop',                  brand = 'Enus',            price = 655000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'zion',          name = 'Zion',                          brand = 'Übermacht',       price = 95000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'zion2',         name = 'Zion Cabrio',                   brand = 'Übermacht',       price = 95000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'previon',       name = 'Previon',                       brand = 'Karin',           price = 72000,  category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'champion',      name = 'Champion',                      brand = 'Dewbauchee',      price = 730000,  category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'futo',          name = 'Futo',                          brand = 'Karin',           price = 43000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'sentinel3',     name = 'Sentinel Classic',              brand = 'Übermacht',       price = 110000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'kanjosj',       name = 'Kanjo SJ',                      brand = 'Dinka',           price = 35000,  category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'postlude',      name = 'Postlude',                      brand = 'Dinka',           price = 55000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'tahoma',        name = 'Tahoma Coupe',                  brand = 'Declasse',        price = 47500,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'broadway',      name = 'Broadway',                      brand = 'Classique',       price = 140000,   category = 'coupes',         type = 'automobile', shop = 'luxury' },
    { model = 'fr36',          name = 'FR36',                          brand = 'Fathom',          price = 50000,   category = 'coupes',        type = 'automobile', shop = 'luxury' },
    
    --- Muscle (4)
    { model = 'blade',         name = 'Blade',                         brand = 'Vapid',           price = 75000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'buccaneer',     name = 'Buccaneer',                     brand = 'Albany',          price = 103000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'buccaneer2',    name = 'Buccaneer Rider',               brand = 'Albany',          price = 195000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'chino',         name = 'Chino',                         brand = 'Vapid',           price = 50000,    category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'chino2',        name = 'Chino Luxe',                    brand = 'Vapid',           price = 147000,    category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'clique',        name = 'Clique',                        brand = 'Vapid',           price = 110000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'coquette3',     name = 'Coquette BlackFin',             brand = 'Invetero',        price = 290000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'deviant',       name = 'Deviant',                       brand = 'Schyster',        price = 210000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'dominator',     name = 'Dominator',                     brand = 'Vapid',           price = 325000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'dominator3',    name = 'Dominator GTX',                 brand = 'Vapid',           price = 550000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'dominator7',    name = 'Dominator ASP',                 brand = 'Vapid',           price = 210000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'dominator8',    name = 'Dominator GTT',                 brand = 'Vapid',           price = 132000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'dukes',         name = 'Dukes',                         brand = 'Imponte',         price = 170000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'faction',       name = 'Faction',                       brand = 'Willard',         price = 85000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'faction2',      name = 'Faction Rider',                 brand = 'Willard',         price = 146500,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'ellie',         name = 'Ellie',                         brand = 'Vapid',           price = 422500,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'gauntlet',      name = 'Gauntlet',                      brand = 'Bravado',         price = 215000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'gauntlet3',     name = 'Classic Gauntlet',              brand = 'Bravado',         price = 110000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'gauntlet4',     name = 'Gauntlet Hellfire',             brand = 'Bravado',         price = 6650000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'gauntlet5',     name = 'Gauntlet Classic Custom',       brand = 'Bravado',         price = 140000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'hermes',        name = 'Hermes',                        brand = 'Albany',          price = 190000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'hotknife',      name = 'Hotknife',                      brand = 'Vapid',           price = 160000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'hustler',       name = 'Hustler',                       brand = 'Vapid',           price = 130000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'impaler',       name = 'Impaler',                       brand = 'Vapid',           price = 165000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'impaler3',      name = 'Impaler Future Shock',          brand = 'Vapid',           price = 160000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'nightshade',    name = 'Nightshade',                    brand = 'Imponte',         price = 255000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'phoenix',       name = 'Phoenix',                       brand = 'Imponte',         price = 95600,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'picador',       name = 'Picador',                       brand = 'Cheval',          price = 135000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'ratloader2',    name = 'Ratloader',                     brand = 'Ratloader2',      price = 235000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'ruiner',        name = 'Ruiner',                        brand = 'Imponte',         price = 68000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'sabregt',       name = 'Sabre GT Turbo',                brand = 'Declasse',        price = 200000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'sabregt2',      name = 'Sabre GT Turbo Custom',         brand = 'Declasse',        price = 240000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'slamvan',       name = 'Slam Van',                      brand = 'Vapid',           price = 99000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'slamvan3',      name = 'Slam Van Custom',               brand = 'Vapid',           price = 109000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'stalion',       name = 'Stallion',                      brand = 'Declasse',        price = 99999,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'tampa',         name = 'Tampa',                         brand = 'Declasse',        price = 163000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'tulip',         name = 'Tulip',                         brand = 'Declasse',        price = 160000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'vamos',         name = 'Vamos',                         brand = 'Declasse',        price = 115000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'vigero',        name = 'Vigero',                        brand = 'Declasse',        price = 123000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'virgo',         name = 'Virgo',                         brand = 'Albany',          price = 145000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'virgo2',        name = 'Virgo Custom Classic',          brand = 'Dundreary',       price = 157000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'virgo3',        name = 'Virgo Classic',                 brand = 'Dundreary',       price = 42000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'voodoo',        name = 'Voodoo',                        brand = 'Declasse',        price = 99000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'yosemite',      name = 'Yosemite',                      brand = 'Declasse',        price = 169000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'yosemite2',     name = 'Yosemite Drift',                brand = 'Declasse',        price = 280000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'buffalo4',      name = 'Buffalo STX',                   brand = 'Bravado',         price = 255000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'manana',        name = 'Manana',                        brand = 'Albany',          price = 61200,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'manana2',       name = 'Manana Custom',                 brand = 'Albany',          price = 52100,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'ruiner4',       name = 'Ruiner ZZ-8',                   brand = 'Imponte',         price = 58000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'vigero2',       name = 'Vigero ZX',                     brand = 'Declasse',        price = 523000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'weevil2',       name = 'Weevil Custom',                 brand = 'BF',              price = 150000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'buffalo5',      name = 'Buffalo EVX',                   brand = 'Bravado',         price = 430000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'tulip2',        name = 'Tulip M-100',                   brand = 'Declasse',        price = 25000,   category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'clique2',       name = 'Clique Wagon',                  brand = 'Vapid',           price = 45000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'brigham',       name = 'Brigham',                       brand = 'Albany',          price = 78500,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'greenwood',     name = 'Greenwood',                     brand = 'Bravado',         price = 110000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'dominator9',    name = 'Dominator GT',                  brand = 'Vapid',           price = 165000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'impaler6',      name = 'Impaler LX',                    brand = 'Declasse',        price = 62000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    { model = 'vigero3',       name = 'Vigero ZX Convertible',         brand = 'Declasse',        price = 335000,  category = 'muscle',         type = 'automobile', shop = 'luxury' },
    
    --- Sports Classic (5)
    { model = 'ardent',        name = 'Ardent',                        brand = 'Ocelot',          price = 125000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'btype',         name = 'Roosevelt',                     brand = 'Albany',          price = 320000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'btype2',        name = 'Franken Stange',                brand = 'Albany',          price = 320000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'btype3',        name = 'Roosevelt Valor',               brand = 'Albany',          price = 155000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'casco',         name = 'Casco',                         brand = 'Lampadati',       price = 200000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'dynasty',       name = 'Dynasty',                       brand = 'Weeny',           price = 55000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'fagaloa',       name = 'Fagaloa',                       brand = 'Vulcar',          price = 35000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'feltzer3',      name = 'Stirling GT',                   brand = 'Benefactor',      price = 416000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'gt500',         name = 'GT500',                         brand = 'Grotti',          price = 180000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'infernus2',     name = 'Infernus Classic',              brand = 'Pegassi',         price = 345000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'jb7002',        name = 'JB 700W',                       brand = 'Dewbauchee',      price = 355000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'mamba',         name = 'Mamba',                         brand = 'Declasse',        price = 540000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'michelli',      name = 'Michelli GT',                   brand = 'Lampadati',       price = 65000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'monroe',        name = 'Monroe',                        brand = 'Pegassi',         price = 245000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'nebula',        name = 'Nebula',                        brand = 'Vulcar',          price = 33000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'peyote',        name = 'Peyote',                        brand = 'Vapid',           price = 85000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'peyote3',       name = 'Peyote Custom',                 brand = 'Vapid',           price = 95000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'pigalle',       name = 'Pigalle',                       brand = 'Lampadati',       price = 61000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'rapidgt3',      name = 'Rapid GT Classic',              brand = 'Dewbauchee',      price = 142000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'retinue',       name = 'Retinue',                       brand = 'Vapid',           price = 66000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'retinue2',      name = 'Retinue MKII',                  brand = 'Vapid',           price = 76000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'savestra',      name = 'Savestra',                      brand = 'Annis',           price = 83000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'stinger',       name = 'Stinger',                       brand = 'Grotti',          price = 235000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'stingergt',     name = 'Stinger GT',                    brand = 'Grotti',          price = 315000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'stromberg',     name = 'Stromberg',                     brand = 'Ocelot',          price = 460000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'swinger',       name = 'Swinger',                       brand = 'Ocelot',          price = 330000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'torero',        name = 'Torero',                        brand = 'Pegassi',         price = 560000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'tornado',       name = 'Tornado',                       brand = 'Declasse',        price = 51000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'tornado2',      name = 'Tornado Convertible',           brand = 'Declasse',        price = 74000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'tornado5',      name = 'Tornado Custom',                brand = 'Declasse',        price = 95000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'turismo2',      name = 'Turismo Classic',               brand = 'Grotti',          price = 675000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'viseris',       name = 'Viseris',                       brand = 'Lampadati',       price = 485000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'z190',          name = '190Z',                          brand = 'Karin',           price = 280000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'ztype',         name = 'Z-Type',                        brand = 'Truffade',        price = 275000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'zion3',         name = 'Zion Classic',                  brand = 'Übermacht',       price = 96000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'cheburek',      name = 'Cheburek',                      brand = 'Rune',            price = 20000,    category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'peyote2',       name = 'Peyote Gasser',                 brand = 'Vapid',           price = 150000,   category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    { model = 'coquette2',     name = 'Coquette Classic',              brand = 'Invetero',        price = 299000,  category = 'sportsclassics', type = 'automobile', shop = 'luxury' },
    
    --- Sports (6)
    { model = 'alpha',         name = 'Alpha',                         brand = 'Albany',          price = 173000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'banshee',       name = 'Banshee',                       brand = 'Bravado',         price = 435000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'bestiagts',     name = 'Bestia GTS',                    brand = 'Grotti',          price = 488000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'buffalo',       name = 'Buffalo',                       brand = 'Bravado',         price = 245000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'buffalo2',      name = 'Buffalo S',                     brand = 'Bravado',         price = 270000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'carbonizzare',  name = 'Carbonizzare',                  brand = 'Grotti',          price = 330000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'comet2',        name = 'Comet',                         brand = 'Pfister',         price = 423000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'comet3',        name = 'Comet Retro Custom',            brand = 'Pfister',         price = 620000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'comet4',        name = 'Comet Safari',                  brand = 'Pfister',         price = 78000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'comet5',        name = 'Comet SR',                      brand = 'Pfister',         price = 590000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'coquette',      name = 'Coquette',                      brand = 'Invetero',        price = 530000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'coquette4',     name = 'Coquette D10',                  brand = 'Invetero',        price = 850000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'drafter',       name = '8F Drafter',                    brand = 'Obey',            price = 265000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'elegy',         name = 'Elegy Retro Custom',            brand = 'Annis',           price = 215000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'elegy2',        name = 'Elegy RH8',                     brand = 'Annis',           price = 348000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'feltzer2',      name = 'Feltzer',                       brand = 'Benefactor',      price = 470000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'flashgt',       name = 'Flash GT',                      brand = 'Vapid',           price = 432000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'furoregt',      name = 'Furore GT',                     brand = 'Lampadati',       price = 492000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'gb200',         name = 'GB 200',                        brand = 'Vapid',           price = 280000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'komoda',        name = 'Komoda',                        brand = 'Lampadati',       price = 235000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'imorgon',       name = 'Imorgon',                       brand = 'Överflöd',        price = 476000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'italigto',      name = 'Itali GTO',                     brand = 'Progen',          price = 560000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'jugular',       name = 'Jugular',                       brand = 'Ocelot',          price = 270000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'jester',        name = 'Jester',                        brand = 'Dinka',           price = 685000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'jester3',       name = 'Jester Classic',                brand = 'Dinka',           price = 200000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'khamelion',     name = 'Khamelion',                     brand = 'Hijak',           price = 530000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'kuruma',        name = 'Kuruma',                        brand = 'Karin',           price = 230000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'locust',        name = 'Locust',                        brand = 'Ocelot',          price = 590000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'lynx',          name = 'Lynx',                          brand = 'Ocelot',          price = 420000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'massacro',      name = 'Massacro',                      brand = 'Dewbauchee',      price = 210000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'neo',           name = 'Neo',                           brand = 'Vysser',          price = 320000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'neon',          name = 'Neon',                          brand = 'Pfister',         price = 523000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'ninef',         name = '9F',                            brand = 'Obey',            price = 612000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'ninef2',        name = '9F Cabrio',                     brand = 'Obey',            price = 520000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'omnis',         name = 'Omnis',                         brand = 'Wow',             price = 390000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'paragon',       name = 'Paragon',                       brand = 'Enus',            price = 716000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'pariah',        name = 'Pariah',                        brand = 'Ocelot',          price = 326000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'penumbra',      name = 'Penumbra',                      brand = 'Maibatsu',        price = 42000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'penumbra2',     name = 'Penumbra FF',                   brand = 'Maibatsu',        price = 75000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'rapidgt',       name = 'Rapid GT',                      brand = 'Dewbauchee',      price = 264000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'rapidgt2',      name = 'Rapid GT Convertible',          brand = 'Dewbauchee',      price = 92000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'revolter',      name = 'Revolter',                      brand = 'Übermacht',       price = 282000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'schafter3',     name = 'Schafter V12',                  brand = 'Benefactor',      price = 190000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'schafter4',     name = 'Schafter LWB',                  brand = 'Benefactor',      price = 210000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'schlagen',      name = 'Schlagen GT',                   brand = 'Benefactor',      price = 435000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'schwarzer',     name = 'Schwartzer',                    brand = 'Benefactor',      price = 198000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'seven70',       name = 'Seven-70',                      brand = 'Dewbauchee',      price = 525000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'specter',       name = 'Specter',                       brand = 'Dewbauchee',      price = 378000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sugoi',         name = 'Sugoi',                         brand = 'Dinka',           price = 140000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sultan',        name = 'Sultan',                        brand = 'Karin',           price = 99000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sultan2',       name = 'Sultan Custom',                 brand = 'Karin',           price = 65000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'surano',        name = 'Surano',                        brand = 'Benefactor',      price = 310000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'tropos',        name = 'Tropos Rallye',                 brand = 'Lampadati',       price = 224500,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'verlierer2',    name = 'Verlierer',                     brand = 'Bravado',         price = 324000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'vstr',          name = 'V-STR',                         brand = 'Albany',          price = 280000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'italirsx',      name = 'Itali RSX',                     brand = 'Progen',          price = 930000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'zr350',         name = 'ZR350',                         brand = 'Annis',           price = 185000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'calico',        name = 'Calico GTF',                    brand = 'Karin',           price = 79000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'futo2',         name = 'Futo GTX',                      brand = 'Karin',           price = 40000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'euros',         name = 'Euros',                         brand = 'Annis',           price = 263000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'jester4',       name = 'Jester RR',                     brand = 'Dinka',           price = 340000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'remus',         name = 'Remus',                         brand = 'Annis',           price = 35000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'comet6',        name = 'Comet S2',                      brand = 'Pfister',         price = 665000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'growler',       name = 'Growler',                       brand = 'Pfister',         price = 430000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'vectre',        name = 'Vectre',                        brand = 'Emperor',         price = 215000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'cypher',        name = 'Cypher',                        brand = 'Übermacht',       price = 235000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sultan3',       name = 'Sultan Classic Custom',         brand = 'Karin',           price = 65000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'rt3000',        name = 'RT3000',                        brand = 'Dinka',           price = 48500,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sultanrs',      name = 'Sultan RS',                     brand = 'Karin',           price = 110000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'visione',       name = 'Visione',                       brand = 'Grotti',          price = 850000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'cheetah2',      name = 'Cheetah Classic',               brand = 'Grotti',          price = 295000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'stingertt',     name = 'Itali GTO Stinger TT',          brand = 'Maibatsu',        price = 772000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'omnisegt',      name = 'Omnis e-GT',                    brand = 'Obey',            price = 315000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sentinel4',     name = 'Sentinel Classic Widebody',     brand = 'Übermacht',       price = 189000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sm722',         name = 'SM722',                         brand = 'Benefactor',      price = 650000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'tenf',          name = '10F',                           brand = 'Obey',            price = 650000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'tenf2',         name = '10F Widebody',                  brand = 'Obey',            price = 690000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'issi8',         name = 'Issi Rally',                    brand = 'Weeny',           price = 150000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'corsita',       name = 'Corsita',                       brand = 'Lampadati',       price = 699900,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'coureur',       name = 'La Coureuse',                   brand = 'Penaud',          price = 360000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'r300',          name = '300R',                          brand = 'Annis',           price = 435000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'panthere',      name = 'Panthere',                      brand = 'Toundra',         price = 390000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    
    --- Super (7)
    { model = 'adder',         name = 'Adder',                         brand = 'Truffade',        price = 880000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'autarch',       name = 'Autarch',                       brand = 'Överflöd',        price = 950000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'banshee2',      name = 'Banshee 900R',                  brand = 'Bravado',         price = 730000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'bullet',        name = 'Bullet',                        brand = 'Vapid',           price = 600000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'cheetah',       name = 'Cheetah',                       brand = 'Grotti',          price = 950000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'cyclone',       name = 'Cyclone',                       brand = 'Coil',            price = 730000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'entity2',       name = 'Entity XXR',                    brand = 'Överflöd',        price = 1150000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'entityxf',      name = 'Entity XF',                     brand = 'Överflöd',        price = 960000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'emerus',        name = 'Emerus',                        brand = 'Progen',          price = 825000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'fmj',           name = 'FMJ',                           brand = 'Vapid',           price = 825000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'furia',         name = 'Furia',                         brand = 'Grotti',          price = 865000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'gp1',           name = 'GP1',                           brand = 'Progen',          price = 750000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'infernus',      name = 'Infernus',                      brand = 'Pegassi',         price = 620000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'italigtb',      name = 'Itali GTB',                     brand = 'Progen',          price = 650000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'italigtb2',     name = 'Itali GTB Custom',              brand = 'Progen',          price = 690000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'krieger',       name = 'Krieger',                       brand = 'Benefactor',      price = 900000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'nero',          name = 'Nero',                          brand = 'Truffade',        price = 960000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'nero2',         name = 'Nero Custom',                   brand = 'Truffade',        price = 1080000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'osiris',        name = 'Osiris',                        brand = 'Pegassi',         price = 650000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'penetrator',    name = 'Penetrator',                    brand = 'Ocelot',          price = 615000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'pfister811',    name = '811',                           brand = 'Pfister',         price = 875000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'prototipo',     name = 'X80 Proto',                     brand = 'Grotti',          price = 1200000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'reaper',        name = 'Reaper',                        brand = 'Pegassi',         price = 650000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'sc1',           name = 'SC1',                           brand = 'Übermacht',       price = 689000,   category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'sheava',        name = 'ETR1',                          brand = 'Emperor',         price = 1280000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 't20',           name = 'T20',                           brand = 'Progen',          price = 705000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'taipan',        name = 'Taipan',                        brand = 'Cheval',          price = 980000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tempesta',      name = 'Tempesta',                      brand = 'Pegassi',         price = 770000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tezeract',      name = 'Tezeract',                      brand = 'Pegassi',         price = 1095000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'thrax',         name = 'Thrax',                         brand = 'Truffade',        price = 785000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tigon',         name = 'Tigon',                         brand = 'Lampadati',       price = 860000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'turismor',      name = 'Turismo R',                     brand = 'Grotti',          price = 748000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tyrant',        name = 'Tyrant',                        brand = 'Överflöd',        price = 875000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tyrus',         name = 'Tyrus',                         brand = 'Progen',          price = 850000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'vacca',         name = 'Vacca',                         brand = 'Pegassi',         price = 785000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'vagner',        name = 'Vagner',                        brand = 'Dewbauchee',      price = 999000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'voltic',        name = 'Voltic',                        brand = 'Coil',            price = 530000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'xa21',          name = 'XA-21',                         brand = 'Ocelot',          price = 725000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'zentorno',      name = 'Zentorno',                      brand = 'Pegassi',         price = 965000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'zorrusso',      name = 'Zorrusso',                      brand = 'Pegassi',         price = 856000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'ignus',         name = 'Ignus',                         brand = 'Pegassi',         price = 895000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'zeno',          name = 'Zeno',                          brand = 'Överflöd',        price = 550000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'deveste',       name = 'Deveste',                       brand = 'Principe',        price = 1100000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'torero2',       name = 'Torero XO',                     brand = 'Pegassi',         price = 985000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'entity3',       name = 'Entity MT',                     brand = 'Overflod',        price = 1240000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'virtue',        name = 'Virtue',                        brand = 'Ocelot',          price = 654000,   category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'turismo3',      name = 'Turismo Omaggio',               brand = 'Grotti',          price = 850000,   category = 'super',         type = 'automobile', shop = 'luxury' },
    
    
    --- Motorcycles (8)
    { model = 'akuma',         name = 'Akuma',                         brand = 'Dinka',           price = 75000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'avarus',        name = 'Avarus',                        brand = 'LCC',             price = 45000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'bagger',        name = 'Bagger',                        brand = 'WMC',             price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'bati',          name = 'Bati 801',                      brand = 'Pegassi',         price = 120000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'bati2',         name = 'Bati 801RR',                    brand = 'Pegassi',         price = 130000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'bf400',         name = 'BF400',                         brand = 'Nagasaki',        price = 78000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'carbonrs',      name = 'Carbon RS',                     brand = 'Nagasaki',        price = 150000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'cliffhanger',   name = 'Cliffhanger',                   brand = 'Western',         price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'daemon',        name = 'Daemon',                        brand = 'WMC',             price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'daemon2',       name = 'Daemon Custom',                 brand = 'Western',         price = 38000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'defiler',       name = 'Defiler',                       brand = 'Shitzu',          price = 65000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'diablous',      name = 'Diablous',                      brand = 'Principe',        price = 85000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'diablous2',     name = 'Diablous Custom',               brand = 'Principe',        price = 145000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'double',        name = 'Double-T',                      brand = 'Dinka',           price = 185000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'enduro',        name = 'Enduro',                        brand = 'Dinka',           price = 25000,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'esskey',        name = 'Esskey',                        brand = 'Pegassi',         price = 36500,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'faggio',        name = 'Faggio Sport',                  brand = 'Pegassi',         price = 2000,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'faggio2',       name = 'Faggio',                        brand = 'Pegassi',         price = 1900,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'faggio3',       name = 'Faggio Mod',                    brand = 'Pegassi',         price = 2500,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'fcr',           name = 'FCR 1000',                      brand = 'Pegassi',         price = 85000,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'fcr2',          name = 'FCR 1000 Custom',               brand = 'Pegassi',         price = 95000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'gargoyle',      name = 'Gargoyle',                      brand = 'Western',         price = 75800,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'hakuchou',      name = 'Hakuchou',                      brand = 'Shitzu',          price = 200000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'hakuchou2',     name = 'Hakuchou Drag',                 brand = 'Shitzu',          price = 210000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'hexer',         name = 'Hexer',                         brand = 'LCC',             price = 55000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'innovation',    name = 'Innovation',                    brand = 'LLC',             price = 65000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'lectro',        name = 'Lectro',                        brand = 'Principe',        price = 98500,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'manchez',       name = 'Manchez',                       brand = 'Maibatsu',        price = 65000,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'nemesis',       name = 'Nemesis',                       brand = 'Principe',        price = 45000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'nightblade',    name = 'Nightblade',                    brand = 'WMC',             price = 98500,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'pcj',           name = 'PCJ-600',                       brand = 'Shitzu',          price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'ratbike',       name = 'Rat Bike',                      brand = 'Western',         price = 10000,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'ruffian',       name = 'Ruffian',                       brand = 'Pegassi',         price = 185000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'sanchez',       name = 'Sanchez Livery',                brand = 'Maibatsu',        price = 15600,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'sanchez2',      name = 'Sanchez',                       brand = 'Maibatsu',        price = 20000,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'sanctus',       name = 'Sanctus',                       brand = 'LCC',             price = 69500,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'sovereign',     name = 'Sovereign',                     brand = 'WMC',             price = 88000,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'stryder',       name = 'Stryder',                       brand = 'Nagasaki',        price = 50000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'thrust',        name = 'Thrust',                        brand = 'Dinka',           price = 110000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'vader',         name = 'Vader',                         brand = 'Shitzu',          price = 55000,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'vindicator',    name = 'Vindicator',                    brand = 'Dinka',           price = 65000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'vortex',        name = 'Vortex',                        brand = 'Pegassi',         price = 39800,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'wolfsbane',     name = 'Wolfsbane',                     brand = 'Western',         price = 41500,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'zombiea',       name = 'Zombie Bobber',                 brand = 'Western',         price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'zombieb',       name = 'Zombie Chopper',                brand = 'Western',         price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'manchez2',      name = 'Manchez Scout',                 brand = 'Maibatsu',        price = 45000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'shinobi',       name = 'Shinobi',                       brand = 'Nagasaki',        price = 145000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'reever',        name = 'Reever',                        brand = 'Western',         price = 125000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'manchez3',      name = 'Manchez Scout Classic',         brand = 'Maibatsu',        price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    { model = 'powersurge',    name = 'Powersurge',                    brand = 'Western',         price = 44500,    category = 'motorcycles',    type = 'bike',       shop = 'luxury' },
    
    --- Off-Road (9)
    { model = 'bfinjection',   name = 'Bf Injection',                  brand = 'Annis',           price = 25000,    category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'bifta',         name = 'Bifta',                         brand = 'Annis',           price = 29000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'blazer',        name = 'Blazer',                        brand = 'Annis',           price = 15200,    category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'blazer3',       name = 'Blazer Hot Rod',                brand = 'Nagasaki',        price = 7000,    category = 'offroad',        type = 'automobile', shop = 'none' },
    { model = 'blazer4',       name = 'Blazer Sport',                  brand = 'Annis',           price = 30250,    category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'brawler',       name = 'Brawler',                       brand = 'Annis',           price = 110000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'caracara2',     name = 'Caracara 4x4',                  brand = 'Vapid',           price = 130000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'dubsta3',       name = 'Dubsta 6x6',                    brand = 'Annis',           price = 325000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'dune',          name = 'Dune Buggy',                    brand = 'Annis',           price = 50000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'everon',        name = 'Everon',                        brand = 'Karin',           price = 89000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'freecrawler',   name = 'Freecrawler',                   brand = 'Canis',           price = 82500,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'hellion',       name = 'Hellion',                       brand = 'Annis',           price = 50000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'kalahari',      name = 'Kalahari',                      brand = 'Canis',           price = 14000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'kamacho',       name = 'Kamacho',                       brand = 'Canis',           price = 165000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'mesa3',         name = 'Mesa Merryweather',             brand = 'Canis',           price = 40000,  category = 'offroad',        type = 'automobile', shop = 'none' },
    { model = 'outlaw',        name = 'Outlaw',                        brand = 'Nagasaki',        price = 35000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'rancherxl',     name = 'Rancher XL',                    brand = 'Declasse',        price = 65000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'rebel2',        name = 'Rebel',                         brand = 'Vapid',           price = 155000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'riata',         name = 'Riata',                         brand = 'Vapid',           price = 78000,  category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'sandking',      name = 'Sandking XL',                   brand = 'Vapid',           price = 196500,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'sandking2',     name = 'Sandking SWB',                  brand = 'Vapid',           price = 132000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'vagrant',       name = 'Vagrant',                       brand = 'Maxwell',         price = 50000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'verus',         name = 'Verus',                         brand = 'Dinka',           price = 15000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'winky',         name = 'Winky',                         brand = 'Vapid',           price = 32000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'yosemite3',     name = 'Yosemite Rancher',              brand = 'Declasse',        price = 82000,  category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'mesa',          name = 'Mesa',                          brand = 'Canis',           price = 65000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'ratel',         name = 'Ratel',                         brand = 'Vapid',           price = 100000,  category = 'offroad',        type = 'automobile', shop = 'none' },
    { model = 'l35',           name = 'Walton L35',                    brand = 'Declasse',        price = 78500,  category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'monstrociti',   name = 'MonstroCiti',                   brand = 'Maibatsu',        price = 48000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'draugur',       name = 'Draugur',                       brand = 'Declasse',        price = 170000,   category = 'offroad',        type = 'automobile', shop = 'luxury' },
    { model = 'terminus',      name = 'Terminus',                      brand = 'Canis',           price = 125000,   category = 'offroad',       type = 'automobile', shop = 'luxury' },
    --- Vans (12)
    { model = 'bison',         name = 'Bison',                         brand = 'Bravado',         price = 100000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'bobcatxl',      name = 'Bobcat XL Open',                brand = 'Vapid',           price = 79000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'burrito3',      name = 'Burrito',                       brand = 'Declasse',        price = 23000,    category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'rumpo',         name = 'Rumpo',                         brand = 'Bravado',         price = 29000,    category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'journey',       name = 'Journey',                       brand = 'Zirconium',       price = 19000,    category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'minivan',       name = 'Minivan',                       brand = 'Vapid',           price = 10000,    category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'minivan2',      name = 'Minivan Custom',                brand = 'Vapid',           price = 10000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'paradise',      name = 'Paradise',                      brand = 'Bravado',         price = 19000,    category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'rumpo3',        name = 'Rumpo Custom',                  brand = 'Bravado',         price = 56000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'speedo',        name = 'Speedo',                        brand = 'Vapid',           price = 36000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'speedo4',       name = 'Speedo Custom',                 brand = 'Vapid',           price = 33000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'surfer',        name = 'Surfer',                        brand = 'BF',              price = 9000,    category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'youga3',        name = 'Youga Classic 4x4',             brand = 'Bravado',         price = 36500,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'youga',         name = 'Youga',                         brand = 'Bravado',         price = 18000,    category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'youga2',        name = 'Youga Classic',                 brand = 'Bravado',         price = 41000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'moonbeam',      name = 'Moonbeam',                      brand = 'Declasse',        price = 55000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'moonbeam2',     name = 'Moonbeam Custom',               brand = 'Declasse',        price = 88000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'journey2',      name = 'Journey II',                    brand = 'Zirconium',       price = 62000,    category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'surfer3',       name = 'Surfer Custom',                 brand = 'BF',              price = 77000,   category = 'vans',           type = 'automobile', shop = 'luxury' },
    { model = 'speedo5',       name = 'Speedo Custom',                 brand = 'Vapid',           price = 45000,  category = 'vans',           type = 'automobile', shop = 'luxury' },
    --- Cycles (13)
    { model = 'bmx',           name = 'BMX',                           brand = 'Bike',            price = 160,     category = 'cycles',         type = 'bike',       shop = 'luxury' },
    { model = 'cruiser',       name = 'Cruiser',                       brand = 'Bike',            price = 510,     category = 'cycles',         type = 'bike',       shop = 'luxury' },
    { model = 'fixter',        name = 'Fixter',                        brand = 'Bike',            price = 225,     category = 'cycles',         type = 'bike',       shop = 'luxury' },
    { model = 'scorcher',      name = 'Scorcher',                      brand = 'Bike',            price = 280,     category = 'cycles',         type = 'bike',       shop = 'luxury' },
    { model = 'tribike',       name = 'Whippet Race Bike',             brand = 'Bike',            price = 500,     category = 'cycles',         type = 'bike',       shop = 'luxury' },
    { model = 'tribike2',      name = 'Endurex Race Bike',             brand = 'Bike',            price = 700,     category = 'cycles',         type = 'bike',       shop = 'luxury' },
    { model = 'tribike3',      name = 'Tri-Cycles Race Bike',          brand = 'Bike',            price = 520,     category = 'cycles',         type = 'bike',       shop = 'luxury' },
    { model = 'inductor',      name = 'Inductor',                      brand = 'Coil',            price = 2500,    category = 'cycles',         type = 'bike',       shop = 'luxury' },
    { model = 'inductor2',     name = 'Junk Energy Inductor',          brand = 'Coil',            price = 2500,    category = 'cycles',         type = 'bike',       shop = 'luxury' },

    { model = 'police4',        name = 'V70 Civil',                     brand = 'Volko',            price = 0,        category = 'Polismyndigheten',         type = 'automobile', shop = 'lillastationen' },
    { model = 'police5',        name = 'XC70 Målad',                    brand = 'Volko',            price = 0,        category = 'Polismyndigheten',         type = 'automobile', shop = 'lillastationen' },
    { model = 'police8',        name = 'Pazzatz',                       brand = 'Mongoswagen',      price = 0,        category = 'Polismyndigheten',         type = 'automobile', shop = 'lillastationen' },
    { model = 'police41',       name = 'V90CC Målad',                   brand = 'Volko',            price = 0,        category = 'Polismyndigheten',         type = 'automobile', shop = 'lillastationen' },
    { model = 'police22',       name = 'T6',                            brand = 'Mongoswagen',      price = 0,        category = 'Polismyndigheten',          type = 'automobile', shop = 'lillastationen' },
    { model = 'police19',       name = 'BMG MC',                        brand = 'BWG',              price = 0,        category = 'Polismyndigheten',          type = 'automobile', shop = 'lillastationen' },
    { model = 'policefelon',    name = 'Felon Civil',                   brand = 'Felon',              price = 0,        category = 'Polismyndigheten',          type = 'automobile', shop = 'lillastationen' },
    { model = 'sebalamo',       name = 'Seb',                           brand = 'sebalamo',              price = 0,        category = 'Polismyndigheten',          type = 'automobile', shop = 'lillastationen' },
    { model = 'pbuffalo4',       name = 'Buffalo',                        brand = 'BWG',              price = 0,        category = 'Polismyndigheten',          type = 'automobile', shop = 'lillastationen' },
    { model = 'gtfminivan',       name = 'Van',                        brand = 'BWG',              price = 0,        category = 'Polismyndigheten',          type = 'automobile', shop = 'lillastationen' },
    
    { model = 'ambulance',        name = 'Ambulans',                    brand = 'Karin',            price = 0,        category = 'Sjukvården',    type = 'automobile', shop = 'Sjukvarden' },
    { model = 'ambulance10',        name = 'Ambulans',                    brand = 'Karin',            price = 0,        category = 'Sjukvården',    type = 'automobile', shop = 'Sjukvarden' },
    { model = 'ambulance11',        name = 'Ambulans',                    brand = 'Karin',            price = 0,        category = 'Sjukvården',    type = 'automobile', shop = 'Sjukvarden' },
    }

for i = 1, #Vehicles do
    QBShared.Vehicles[Vehicles[i].model] = {
        spawncode = Vehicles[i].model,
        name = Vehicles[i].name,
        brand = Vehicles[i].brand,
        model = Vehicles[i].model,
        price = Vehicles[i].price,
        category = Vehicles[i].category,
        hash = joaat(Vehicles[i].model),
        type = Vehicles[i].type,
        shop = Vehicles[i].shop
    }
end
