DurabilityBlockedWeapons = { -- weapons that can't be repaired
    'weapon_stungun',
    'weapon_stungun_mp',
    'weapon_nightstick',
    'weapon_flashlight',
    'weapon_unarmed'
}

DurabilityMultiplier = { -- durability multiplier for each weapon type
    -- Melee
    weapon_dagger                = 0.10,
    weapon_bat                   = 0.10,
    weapon_bottle                = 0.10,
    weapon_crowbar               = 0.10,
    weapon_candycane             = 0.10,
    weapon_golfclub              = 0.10,
    weapon_hammer                = 0.10,
    weapon_hatchet               = 0.10,
    weapon_knuckle               = 0.10,
    weapon_knife                 = 0.10,
    weapon_machete               = 0.10,
    weapon_switchblade           = 0.10,
    weapon_wrench                = 0.10,
    weapon_battleaxe             = 0.10,
    weapon_poolcue               = 0.10,
    weapon_briefcase             = 0.10,
    weapon_briefcase_02          = 0.10,
    weapon_garbagebag            = 0.10,
    weapon_handcuffs             = 0.10,
    weapon_stone_hatchet         = 0.10,

    -- Handguns
    weapon_combatpistol          = 0.10,
    weapon_appistol              = 0.10,
    weapon_stungun 				 = 0.10,
    weapon_snspistol             = 0.10,
    weapon_flaregun              = 0.10,
    weapon_marksmanpistol        = 0.10,
    weapon_revolver              = 0.10,
    weapon_revolver_mk2          = 0.10,
    weapon_doubleaction          = 0.10,
    weapon_raypistol             = 0.10,
    weapon_ceramicpistol         = 0.10,
    weapon_navyrevolver          = 0.10,
    weapon_gadgetpistol          = 0.10,

    -- Submachine Guns
    weapon_smg                   = 0.10,
    weapon_machinepistol         = 0.10,
    weapon_raycarbine            = 0.10,
    weapon_tecpistol             = 0.10,

    -- Shotguns
    weapon_pumpshotgun           = 0.10,
    weapon_assaultshotgun        = 0.10,
    weapon_bullpupshotgun        = 0.10,
    weapon_musket                = 0.10,
    weapon_heavyshotgun          = 0.10,
    weapon_dbshotgun             = 0.10,
    weapon_autoshotgun           = 0.10,
    weapon_combatshotgun         = 0.10,

    -- Assault Rifles
    weapon_assaultrifle_mk2      = 0.10,
    weapon_carbinerifle          = 0.10,
    weapon_advancedrifle         = 0.10,
    weapon_specialcarbine        = 0.10,
    weapon_specialcarbine_mk2    = 0.10,
    weapon_bullpuprifle_mk2      = 0.10,
    weapon_militaryrifle         = 0.10,
    weapon_heavyrifle            = 0.10,
    weapon_tacticalrifle         = 0.10,

    -- Light Machine Guns
    weapon_mg                    = 0.10,
    weapon_combatmg              = 0.10,
    weapon_gusenberg             = 0.10,
    weapon_combatmg_mk2          = 0.10,

    -- Sniper Rifles
    weapon_sniperrifle           = 0.10,
    weapon_marksmanrifle         = 0.10,
    weapon_remotesniper          = 0.10,
    weapon_marksmanrifle_mk2     = 0.10,
    weapon_precisionrifle        = 0.10,

    -- Heavy Weapons
    weapon_rpg                   = 0.10,
    weapon_grenadelauncher       = 0.10,
    weapon_grenadelauncher_smoke = 0.10,
    weapon_emplauncher           = 0.10,
    weapon_minigun               = 0.10,
    weapon_firework              = 0.10,
    weapon_railgun               = 0.10,
    weapon_hominglauncher        = 0.10,
    weapon_compactlauncher       = 0.10,
    weapon_rayminigun            = 0.10,
    weapon_railgunxm3            = 0.10,

    -- Throwables
    weapon_grenade               = 0.10,
    weapon_bzgas                 = 0.10,
    weapon_molotov               = 0.10,
    weapon_stickybomb            = 0.10,
    weapon_proxmine              = 0.10,
    weapon_snowball              = 0.10,
    weapon_pipebomb              = 0.10,
    weapon_ball                  = 0.10,
    weapon_smokegrenade          = 0.10,
    weapon_flare                 = 0.10,
    weapon_flashbang             = 0.10,
    flashbang                    = 0.10,

    -- Miscellaneous
    -- weapon_petrolcan             = 0.10,
    weapon_fireextinguisher      = 0.10,
    weapon_hazardcan             = 0.10,
    weapon_fertilizercan         = 0.10,

    --Custom Weapons
    weapon_ak47                  = 0.15,
    weapon_fnx45                 = 0.15,
    weapon_glock17               = 0.15,
    weapon_m4                    = 0.15,
    weapon_mk14                  = 0.15,
    weapon_m110                  = 0.15,
    weapon_huntingrifle          = 0.30,
    weapon_m9                    = 0.15,
    weapon_m70                   = 0.15,
    weapon_m1911                 = 0.15,
    weapon_mac10                 = 0.15,
    weapon_uzi                   = 0.15,
    weapon_mossberg              = 0.15,
    weapon_remington             = 0.15,
    weapon_shiv                  = 0.15,
    weapon_katana                = 0.15,
    weapon_pinkkatana            = 0.15,
    weapon_purplekatana          = 0.15,
    weapon_redkatana             = 0.15,
    weapon_thermalkatana         = 0.15,
    weapon_whitekatana           = 0.15,
    weapon_yellowkatana          = 0.15,
    weapon_cyankatana            = 0.15,
    weapon_limekatana            = 0.15,
    weapon_sledgehammer          = 0.15,
    weapon_glock18c              = 0.15,
    weapon_aks74                 = 0.15,
    weapon_ak74                  = 0.15,
    weapon_perforator            = 0.05,
    weapon_bluebfknife           = 0.05,
    weapon_bfknife               = 0.05,
    weapon_chbfknife             = 0.05,
    weapon_crimsonbfknife        = 0.05,
    weapon_fadebfknife           = 0.05,
    weapon_flipknife             = 0.05,
    weapon_forestbfknife         = 0.05,
    weapon_gutknife              = 0.05,
    weapon_huntsmanknife         = 0.05,
    weapon_karambitknife         = 0.05,
    weapon_safaribfknife         = 0.05,
    weapon_scorchedbfknife       = 0.05,
    weapon_slaughterbfknife      = 0.05,
    weapon_stainedrbfknife       = 0.05,
    weapon_urbanrbfknife         = 0.05,
    weapon_riftedge              = 0.15,
    weapon_sword                 = 0.15,
    weapon_keyboard              = 0.15,

    -- WEAPONS DEFAULT
    WEAPON_PISTOL                = 1.0,

    -- WEAPONS POLICE
    WEAPON_GLOCK22               = 1.0,
    WEAPON_PISTOLXM3             = 1.0,
    WEAPON_DE                    = 1.0,
    WEAPON_MINISMG               = 1.0,
    WEAPON_MP9                   = 1.0,
    WEAPON_MP5                   = 1.0,
    WEAPON_CARBINERIFLE_MK2      = 1.0,
    WEAPON_SCARH                 = 1.0,
    WEAPON_AR15                  = 1.0,
    WEAPON_HK416                 = 1.0,
    WEAPON_PUMPSHOTGUN_MK2       = 1.0,
    WEAPON_HEAVYSNIPER_MK2       = 1.0,

    -- WEAPONS GANG
    WEAPON_SNSPISTOL_MK2         = 2.0,
    WEAPON_PISTOL_MK2            = 2.0,
    WEAPON_HEAVYPISTOL           = 2.0,
    WEAPON_VINTAGEPISTOL         = 2.0,
    WEAPON_PISTOL50              = 2.0,
    WEAPON_MICROSMG              = 2.0,
    WEAPON_SMG_MK2               = 2.0,
    WEAPON_COMBATPDW             = 2.0,
    WEAPON_ASSAULTSMG            = 2.0,
    WEAPON_COMPACTRIFLE          = 2.0,
    WEAPON_GROZA                 = 2.0,
    WEAPON_ASSAULTRIFLE          = 2.0,
    WEAPON_BULLPUPRIFLE          = 2.0,
    WEAPON_SAWNOFFSHOTGUN        = 2.0,
    WEAPON_HEAVYSNIPER           = 2.0,
}